const CATEGORY_ACTION_TYPES = {
  SET_CATEGORIES_START: "SET_CATEGORIES_START",
  SET_CATEGORIES_SUCCESS: "SET_CATEGORIES_SUCCESS",
  SET_CATEGORIES_FAILURE: "SET-CATEGORIES_FAILURE",
};

export default CATEGORY_ACTION_TYPES;
